#
# Module manifest for module 'IcingaAPI'
#
# Generated by: Viktor Mandlbauer
#
# Generated on: 03.04.2023
#

@{

    ModuleVersion     = '0.0.1'
    GUID              = 'aab52d87-615d-4cf6-b717-46be722a2324'
    Author            = 'Viktor Mandlbauer'
    CompanyName       = 'Unknown'
    FunctionsToExport = @('New-IcingaDowntime', 'Register-IcingaApiEndpoint', 'Remove-icingaDowntime')
    RootModule        = 'IcingaAPI.psm1'
}  